name: Publish Plugin to Portal

on:
  push:
    tags:
      - '*'

jobs:
  gradle:
    runs-on: ubuntu-latest
    env:
      GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
      GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Cache Gradle Caches
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/
          key: cache-gradle-cache

      - name: Cache Gradle Wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/
          key: cache-gradle-wrapper

      - name: Run Gradle tasks
        run: ./gradlew preMerge --continue

      - name: Test version via tag
        run: ./gradlew --project-dir -PreleaseVersion=${{ github.ref_name}} clean :plugin-build:clean :plugin-build:plugin:clean

      #- name: Publish on Plugin Portal
      #  run: ./gradlew --project-dir -PreleaseVersion=${{ github.event.inputs.version }} plugin-build setupPluginUploadFromEnvironment publishPlugins
      #  if: success()

      - name: Stop Gradle
        run: ./gradlew --stop
